export interface StockEntry {
  code: string;
  name: string;
  exchange: "KOSPI" | "KOSDAQ" | "NASDAQ" | "NYSE" | "ETF";
}

export const STOCK_DIRECTORY: StockEntry[] = [
  { code: "005930", name: "삼성전자", exchange: "KOSPI" },
  { code: "000660", name: "SK하이닉스", exchange: "KOSPI" },
  { code: "373220", name: "LG에너지솔루션", exchange: "KOSPI" },
  { code: "207940", name: "삼성바이오로직스", exchange: "KOSPI" },
  { code: "005380", name: "현대차", exchange: "KOSPI" },
  { code: "000270", name: "기아", exchange: "KOSPI" },
  { code: "005490", name: "POSCO홀딩스", exchange: "KOSPI" },
  { code: "035420", name: "NAVER", exchange: "KOSPI" },
  { code: "035720", name: "카카오", exchange: "KOSPI" },
  { code: "051910", name: "LG화학", exchange: "KOSPI" },
  { code: "006400", name: "삼성SDI", exchange: "KOSPI" },
  { code: "068270", name: "셀트리온", exchange: "KOSPI" },
  { code: "105560", name: "KB금융", exchange: "KOSPI" },
  { code: "055550", name: "신한지주", exchange: "KOSPI" },
  { code: "012330", name: "현대모비스", exchange: "KOSPI" },
  { code: "028260", name: "삼성물산", exchange: "KOSPI" },
  { code: "066570", name: "LG전자", exchange: "KOSPI" },
  { code: "003670", name: "포스코퓨처엠", exchange: "KOSPI" },
  { code: "323410", name: "카카오뱅크", exchange: "KOSPI" },
  { code: "032830", name: "삼성생명", exchange: "KOSPI" },

  { code: "247540", name: "에코프로비엠", exchange: "KOSDAQ" },
  { code: "086520", name: "에코프로", exchange: "KOSDAQ" },
  { code: "196170", name: "알테오젠", exchange: "KOSDAQ" },
  { code: "091990", name: "셀트리온제약", exchange: "KOSDAQ" },
  { code: "287410", name: "JYP Ent.", exchange: "KOSDAQ" },
  { code: "357780", name: "솔브레인", exchange: "KOSDAQ" },

  { code: "NVDA", name: "엔비디아 (NVIDIA)", exchange: "NASDAQ" },
  { code: "AAPL", name: "애플 (Apple)", exchange: "NASDAQ" },
  { code: "MSFT", name: "마이크로소프트 (Microsoft)", exchange: "NASDAQ" },
  { code: "AMZN", name: "아마존 (Amazon)", exchange: "NASDAQ" },
  { code: "GOOGL", name: "알파벳 A / 구글 (Google)", exchange: "NASDAQ" },
  { code: "META", name: "메타 (Meta)", exchange: "NASDAQ" },
  { code: "TSLA", name: "테슬라 (Tesla)", exchange: "NASDAQ" },
  { code: "AVGO", name: "브로드컴 (Broadcom)", exchange: "NASDAQ" },
  { code: "AMD", name: "AMD", exchange: "NASDAQ" },
  { code: "NFLX", name: "넷플릭스 (Netflix)", exchange: "NASDAQ" },
  { code: "PLTR", name: "팔란티어 (Palantir)", exchange: "NASDAQ" },
  { code: "INTC", name: "인텔 (Intel)", exchange: "NASDAQ" },
  { code: "DIS", name: "디즈니 (Disney)", exchange: "NYSE" },
  { code: "LLY", name: "일라이릴리 (Eli Lilly)", exchange: "NYSE" },
  { code: "BRK.B", name: "버크셔해서웨이 (Berkshire)", exchange: "NYSE" },

  { code: "069500", name: "KODEX 200", exchange: "ETF" },
  { code: "371460", name: "TIGER 미국S&P500", exchange: "ETF" },
  { code: "133690", name: "TIGER 미국나스닥100", exchange: "ETF" },
  { code: "458730", name: "SOL 미국배당다우존스", exchange: "ETF" },
  { code: "252670", name: "KODEX 200선물인버스2X", exchange: "ETF" },
  { code: "114800", name: "KODEX 인버스", exchange: "ETF" },
  { code: "122630", name: "KODEX 레버리지", exchange: "ETF" },
  { code: "465580", name: "ACE 미국S&P500", exchange: "ETF" },
  { code: "465320", name: "ACE 미국나스닥100", exchange: "ETF" },
  { code: "381180", name: "TIGER 미국테크TOP10 INDXX", exchange: "ETF" },
  { code: "278530", name: "KODEX 미국S&P500TR", exchange: "ETF" },
  { code: "132030", name: "KODEX 골드선물(H)", exchange: "ETF" },

  { code: "SPY", name: "SPDR S&P 500 ETF (SPY)", exchange: "ETF" },
  { code: "QQQ", name: "Invesco QQQ Trust (QQQ)", exchange: "ETF" },
  { code: "VOO", name: "Vanguard S&P 500 ETF (VOO)", exchange: "ETF" },
  { code: "SCHD", name: "Schwab US Dividend Equity (SCHD)", exchange: "ETF" },
  { code: "TLT", name: "iShares 20+ Year Treasury (TLT)", exchange: "ETF" },
  { code: "SOXX", name: "iShares Semiconductor (SOXX)", exchange: "ETF" },
  { code: "TQQQ", name: "ProShares UltraPro QQQ (TQQQ)", exchange: "ETF" },
  { code: "SQQQ", name: "ProShares UltraPro Short QQQ (SQQQ)", exchange: "ETF" },
  { code: "JEPI", name: "JPMorgan Equity Premium (JEPI)", exchange: "ETF" },
];